[package]
name = "learning_rust_repo"
version = "0.1.0"
authors = ["ammarshahin <ammar0ammar612@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "learning_rust_repo"
path = "src/traversy_media_crash_course/main.rs"
