name: Build and test

on:
  push:
    branches: 
      - master

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build
        run: cargo build --verbose
     
      - name: Run tests
        run: cargo test --verbose

      - name: Lint
        uses: actions/super_linter@v4
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}